# Site settings
title: Web Design, Development and SEO in Duluth Minnesota | Jason Swingen
email: jason.swingen@gmail.com
url: https://jasonswingen.com
description: "Website Design, Development, and SEO in Duluth Minnesota. Jason Swingen focuses on fast, responsive, and SEO friendly sites. Affordable plans available!"
skills: "Web Developer - Search Engine Optimizer - Internet Marketer"
titles:
  one: Web Developer
  two: Search Engine Optimizer
  three: Internet Marketer
meta_author: Swingen Jason

# Google webmaster tools
google_verify:

# https://ssl.bing.com/webmaster/configure/verify/ownership Option 2 content= goes here
bing_verify: AC92C578DD8459A0ECE543DE43E3F695

# Contact form:
#Â - static : pass through formspree.io to validate email sending
# - disqus : replace contact form by disqus thread
# - comment the line below if you want to stick with the default PHP contact form
contact: static

# If you use disqus you need disqus shortname
# https://help.disqus.com/customer/portal/articles/466208
disqus_shortname: jasonswingen

# Color settings (hex-codes without the leading hash-tag)
color:
  primary: 18bc9c #80B3FF
  primary-rgb: "24,288,156" #"128,179,255"
  secondary: 2c3e50 #FD6E8A
  secondary-dark: 233140 #A2122F

# Footer settings
footer:
  copyright: Swingen Development LLC
  location: Location
  social: Let's Connect
  credits: Stay In Touch

# Social networks usernames (many more available: google-plus, flickr, dribbble, pinterest, instagram, tumblr, linkedin, etc.)
social:
  - title: linkedin
    url: http://www.linkedin.com/in/jasonswingen

# Postal address (add as many lines as necessary)
address:
  - line: Duluth, Minnesota

# Credits content
credits: 'You can <span class="page-scroll"><a href="#contact" data-toggle="tooltip" data-placement="top" title="It only takes a minute.">contact me</a></span> by <span data-toggle="tooltip" data-placement="top" title="(218) 409-6555"><a href="tel:218-409-6555">phone</a></span> or <span data-toggle="tooltip" data-placement="top" title="jason.swingen@gmail.com"><a href="mailto:jason.swingen@gmail.com">email</a></span> if you are looking for any design, development, or marketing.'

# Build settings
markdown: kramdown
permalink: pretty

# Make pages placed in `_pages/` render as published pages
collections:
  pages:
    output: true
    permalink: /:name/

# Default layout for collection items in `_pages`
defaults:
  - scope:
      path: ""
      type: "pages"
    values:
      layout: "page"
